---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: vivo-api-db-claim
  namespace: vivo-4-0
spec:
  ref:
    apiVersion: sql.tanzu.vmware.com/v1
    kind: Postgres
    name: vivo-api-postgres
    namespace: service-instances